apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      hostNetwork: true
      serviceAccountName: pz-ksa
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: order
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
          - secretRef:
              name: db-secret
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
              
      - name: cloudsql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.17.0
        env:
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PORT
        args:
          - "--structured-logs"
          - "--port=$(POSTGRES_PORT)"
          - "--private-ip"
          - "pz-project-473804:asia-northeast3:pz-db"
        securityContext:
          runAsNonRoot: true