apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      serviceAccountName: pz-ksa
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: order
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
          - secretRef:
              name: db-secret
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
