apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: NodePort