apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: bronze-etl
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: Python
  mode: cluster
  image: asia-northeast3-docker.pkg.dev/pz-project-473804/ay-repo/bronze:20251026-1.0.3
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/applications/bronze.py"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  deps:
    jars:
      - "local:///opt/spark/work-dir/jars/gcs-connector-hadoop3-latest.jar"

  sparkConf:
    # GCS Connector 설정
    "spark.hadoop.fs.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
    "spark.hadoop.fs.AbstractFileSystem.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"

  driver:
    cores: 1
    memory: 1024m
    serviceAccount: pz-ksa 
    labels:
      version: 3.5.0
    env:
      - name: DB_HOST
        value: "127.0.0.1"
      - name: DB_PORT
        value: "5432"

  executor:
    cores: 2
    instances: 2
    memory: 2048m
    serviceAccount: pz-ksa

