apiVersion: v1
kind: Secret
metadata:
  name: etl-secret
  namespace: default
type: Opaque
data:
  DB_USER: bXlfdXNlcg==        
  DB_PW: MTIzNA==
  DB_HOST: Y2xvdWRzcWwtcHJveHktc3Zj
  DB_NAME: cGl6emE=
  DB_PORT: NTQzMg==