apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: silver-etl
  namespace: spark  
spec:
  type: Python
  mode: cluster
  image: asia-northeast3-docker.pkg.dev/pz-project-473804/ay-repo/silver:20251002-1.0.1
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/applications/silver.py"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    memory: 1024m
    serviceAccount: pz-ksa 
    labels:
      version: 3.5.0
  executor:
    instances: 2
    cores: 1
    memory: 2g
    labels:
      version: 3.5.0
  deps:
    jars:
      - "local:///opt/spark/jars/gcs-connector-hadoop3-latest.jar"
