apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: spark
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://googlecloudplatform.github.io/spark-on-k8s-operator
    chart: spark
    targetRevision: 1.1.27 
    helm:
      parameters:
        - name: sparkJobNamespace
          value: "spark"   
        - name: webhook.enable
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
      - ServerSideApply=true
      - CreateNamespace=true
