apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      serviceAccountName: pz-ksa
      containers:
      - name: login
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
          - secretRef:
              name: db-secret
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
        readinessProbe: 
          httpGet:
            path: /
            port: 8000
            httpHeaders:          
            - name: Host
              value: localhost  

              