apiVersion: v1
kind: Service
metadata:
  name: login-service
  labels:
    app: login
spec:
  selector:
    app: login
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP