apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pizza-airflow
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://airflow-helm.github.io/charts
    chart: airflow
    targetRevision: 8.8.0
    helm:
      values: |
        airflow:
          image:
            repository: apache/airflow
            tag: 2.6.3-python3.9
          executor: KubernetesExecutor
          
          envFrom:
            - secretRef:
                name: airflow-db-secret
                
          config:
            core:
              load_examples: "False"
              sql_alchemy_conn: postgresql+psycopg2://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
              
        web:
          service:
            type: ClusterIP
            port: 8080
          defaultUser:
            enabled: true
            role: Admin
            username: admin
            password: admin
            email: admin@example.com
            firstName: Air
            lastName: Flow
          readinessProbe:
            enabled: true
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            path: /health
            scheme: HTTP
            port: 8080

        scheduler:
          replicas: 1

        dags:
          persistence:
            enabled: false
          gitSync:
            enabled: true
            repo: "https://github.com/hirundos/pizza_cd.git"
            branch: main
            subPath: "dags"
            revision: HEAD
            depth: 1
            wait: 60

        # 3. externalDatabase.enabled를 true로 변경
        externalDatabase:
          enabled: true
          
        postgresql:
          enabled: false
        redis:
          enabled: false
        workers:
          enabled: false
        flower:
          enabled: false
        pgbouncer:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true