apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pizza-airflow
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://airflow-helm.github.io/charts
    chart: airflow
    targetRevision: 8.8.0
    helm:
      values: |
        airflow:
          image:
            repository: apache/airflow
            tag: 2.7.3-python3.10
          executor: KubernetesExecutor
          config:
            core:
              load_examples: "False"
              remote_logging: "True"
              remote_base_log_folder: "gs://pz-buck-888/logs" 
              remote_log_conn_id: "google_cloud_default"
              task_log_reader: "remote"
            kubernetes:
              delete_worker_pods: "False"
              delete_worker_pods_on_failure: "False"
              enable_tcp_keepalive: "False" 
              pod_template_file: "" 
              worker_container_repository: "apache/airflow"
              worker_container_tag: "2.7.3-python3.10"
              enable_kubernetes_executor_logs: "False"
            logging:
              encrypt_s3_logs: "False"

        web:
          service:
            type: LoadBalancer
            port: 8080
          defaultUser:
            enabled: true
            role: Admin
            username: admin
            password: admin
            email: admin@example.com
            firstName: Air
            lastName: Flow
          readinessProbe:
            enabled: true
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            path: /health
            scheme: HTTP
            port: 8080

        scheduler:
          replicas: 1

        dags:
          persistence:
            enabled: false
          gitSync:
            enabled: true
            repo: "https://github.com/hirundos/pizza_cd.git"
            branch: main
            subPath: "dags"
            revision: HEAD
            depth: 1
            wait: 60

        externalDatabase:
          enabled: true
          host: cloudsql-proxy-svc.default
          port: 5432
          user: my_user
          database: postgres
          password: 1234
          
        postgresql:
          enabled: false
        redis:
          enabled: false
        workers:
          enabled: false
        flower:
          enabled: false
        pgbouncer:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
