apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: airflow
spec:
  project: default
  source:
    repoURL: 'https://airflow-helm.github.io/charts'
    chart: airflow
    targetRevision: 2.10.5 
    helm:
      values: |
        image:
          repository: apache/airflow
          tag: 2.9.1-python3.10
        executor: KubernetesExecutor

        fernetKey: "4x2oJqdoLwxaP-P4-d_yj4G8G0N-sZ7x4t_G-bE2hDc="
        webserverSecretKey: "9a9f2e3a8b4c7d6e5f1a3b9c8d7e6f2a5b1c4d0e9f8a7b6c"

        dags:
          persistence:
            enabled: false
          gitSync:
            enabled: true
            repo: "https://github.com/hirundos/pizza_cd.git"
            branch: main
            subPath: "dags"
            revision: HEAD
            depth: 1
            wait: 60
        logs:
          persistence:
            enabled: true
            size: 10Gi
        config:
          AIRFLOW__CORE__LOAD_EXAMPLES: "false"
          AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"

        scheduler:
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
        web:
          replicas: 1
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
        triggerer:
          enabled: true
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"

        postgresql:
          enabled: false
        pgbouncer:
            enabled: false
        workers:
          enabled: false
        flower:
          enabled: false
        
        externalDatabase:
          type: postgresql
          host: cloudsql-proxy-svc.default
          port: 5432
          database: pz-db
          secretName: airflow-db-secret
          userKey: POSTGRES_USER
          passwordKey: POSTGRES_PASSWORD

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true