apiVersion: v1
kind: Secret
metadata:
  name: airflow-db-secret
  namespace: airflow
type: Opaque
data:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: cG9zdGdyZXNxbCtwc3ljb3BnMjovL215X3VzZXI6MTIzNEBjbG91ZHNxbC1wcm94eS1zdmMuZGVmYXVsdDo1NDMyL3Bpenph
