apiVersion: v1
kind: Secret
metadata:
  name: irflow-db-secret
type: Opaque
data:
  POSTGRES_USER: bXlfdXNlcg==        
  POSTGRES_PASSWORD: MTIzNA==
  POSTGRES_HOST: Y2xvdWRzcWwtcHJveHktc3Zj         
  POSTGRES_DB: cGl6emE=
  POSTGRES_PORT: NTQzMg==