airflow:
  executor: KubernetesExecutor   
  image:
    repository: apache/airflow
    tag: 2.9.1-python3.10         
  fernetKey: "4x2oJqdoLwxaP-P4-d_yj4G8G0N-sZ7x4t_G-bE2hDc="                  
  secretKey: "9a9f2e3a8b4c7d6e5f1a3b9c8d7e6f2a5b1c4d0e9f8a7b6c"                  
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: "https://github.com/hirundos/pizza_cd.git"
    branch: main
    subPath: "dags"
    revision: HEAD
    depth: 1
    wait: 60 
web:
  service:
    type: ClusterIP
    port: 8080
scheduler:
  replicas: 1
logs:
  persistence:
    enabled: true
    size: 10Gi
env:
  - name: airflow
    value: airflow
  - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
    value: "false"
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
