apiVersion: v1
kind: Service
metadata:
  name: menu-service
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"8000":"django-backend-config"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: menu
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: NodePort